name: elagy_user_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: any
  bloc: any
  flutter_bloc: any
  flutter_offline: any
  http: any
  video_player: any
  shared_preferences: any
  smooth_page_indicator: any
  cached_network_image: any
  fluttertoast: any
  flutter_share: any
  flutter_zoom_drawer: any
  dotted_border: any
  image_picker: any
  sqflite: any
  geocoding: any
  url_launcher: any
  geolocator: any
  firebase: any
  firebase_core: any
  firebase_messaging: any
  change_app_package_name: any
  flutter_launcher_icons: ^0.10.0
  enhance_stepper: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/video/
    - assets/images/
    - assets/images/newlogo/
    - assets/images/splash/
    - assets/images/Login3/
    - assets/images/reset password/
    - assets/images/profile/
    - assets/images/menu/
    - assets/images/menus/
    - assets/images/previous images/
    - assets/images/order/
    - assets/images/contact us/
    - assets/images/about_us/
    - assets/images/onboarding/
    - assets/images/onboarding/1/
    - assets/images/onboarding/2/
    - assets/images/onboarding/3/
  fonts:
    - family: DIN Next LT Arabic
      fonts:
        - asset: assets/fonts/DIN Next LT Arabic Light.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf