/*
import '../HomePage/one_pharmacy_model.dart';

class SearchModel {
  SearchModel({
    this.status,
    this.code,
    this.msg,
    this.data,
  });

  bool? status;
  int? code;
  String? msg;
  Data? data;

  SearchModel.fromJson(Map<String, dynamic>? json) {
    status = json?['status'];
    code = json?['code'];
    msg = json?['msg'];
    data = Data.fromJson(json?['data']);
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['status'] = status;
    _data['code'] = code;
    _data['msg'] = msg;
    _data['data'] = data!.toJson();
    return _data;
  }
}

class Data {
  Data({
    this.currentPage,
    this.dataSub,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });

  int? currentPage;
  List<ActiveMedicines>? dataSub;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<Links>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  Data.fromJson(Map<String, dynamic>? json) {
    currentPage = json?['current_page'];
    dataSub = List.from(json?['dataSub'])
        .map((e) => ActiveMedicines.fromJson(e))
        .toList();
    firstPageUrl = json?['first_page_url'];
    from = json?['from'];
    lastPage = json?['last_page'];
    lastPageUrl = json?['last_page_url'];
    links = List.from(json?['links']).map((e) => Links.fromJson(e)).toList();
    nextPageUrl = json?['next_page_url'];
    path = json?['path'];
    perPage = json?['per_page'];
    prevPageUrl = json?['prev_page_url'];
    to = json?['to'];
    total = json?['total'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['current_page'] = currentPage;
    _data['dataSub'] = dataSub!.map((e) => e.toJson()).toList();
    _data['first_page_url'] = firstPageUrl;
    _data['from'] = from;
    _data['last_page'] = lastPage;
    _data['last_page_url'] = lastPageUrl;
    _data['links'] = links!.map((e) => e.toJson()).toList();
    _data['next_page_url'] = nextPageUrl;
    _data['path'] = path;
    _data['per_page'] = perPage;
    _data['prev_page_url'] = prevPageUrl;
    _data['to'] = to;
    _data['total'] = total;
    return _data;
  }
}

class Pivot {
  Pivot({
    this.pharmacyId,
    this.medicineId,
    this.id,
    this.price,
    this.amount,
    this.active,
  });

  int? pharmacyId;
  int? medicineId;
  int? id;
  String? price;
  String? amount;
  bool? active;

  Pivot.fromJson(Map<String, dynamic>? json) {
    pharmacyId = json?['pharmacy_id'];
    medicineId = json?['medicine_id'];
    id = json?['id'];
    price = json?['price'];
    amount = json?['amount'];
    active = json?['active'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['pharmacy_id'] = pharmacyId;
    _data['medicine_id'] = medicineId;
    _data['id'] = id;
    _data['price'] = price;
    _data['amount'] = amount;
    _data['active'] = active;
    return _data;
  }
}

class Links {
  Links({
    this.url,
    this.label,
    this.active,
  });

  String? url;
  String? label;
  bool? active;

  Links.fromJson(Map<String, dynamic>? json) {
    url = json?["url"];
    label = json?['label'];
    active = json?['active'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['url'] = url;
    _data['label'] = label;
    _data['active'] = active;
    return _data;
  }
}
*/

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchModelDataLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  SearchModelDataLinks({
    this.url,
    this.label,
    this.active,
  });

  SearchModelDataLinks.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    label = json['label']?.toString();
    active = json['active'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['label'] = label;
    data['active'] = active;
    return data;
  }
}

class SearchModelDataDataPivot {
/*
{
  "pharmacy_id": 1,
  "medicine_id": 6,
  "id": 6,
  "price": "30.00",
  "amount": "30.00",
  "active": true
}
*/

  int? pharmacyId;
  int? medicineId;
  int? id;
  String? price;
  String? amount;
  bool? active;

  SearchModelDataDataPivot({
    this.pharmacyId,
    this.medicineId,
    this.id,
    this.price,
    this.amount,
    this.active,
  });

  SearchModelDataDataPivot.fromJson(Map<String, dynamic> json) {
    pharmacyId = json['pharmacy_id']?.toInt();
    medicineId = json['medicine_id']?.toInt();
    id = json['id']?.toInt();
    price = json['price']?.toString();
    amount = json['amount']?.toString();
    active = json['active'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pharmacy_id'] = pharmacyId;
    data['medicine_id'] = medicineId;
    data['id'] = id;
    data['price'] = price;
    data['amount'] = amount;
    data['active'] = active;
    return data;
  }
}

class SearchModelDataData {
/*
{
  "id": 6,
  "name": "Medicine 6",
  "photo": "http://secret-taiga-11502.herokuapp.com/images/medicines",
  "description": "Medicine is the field of health and healing. It includes nurses, doctors, and various specialists. It covers diagnosis, treatment, and prevention of disease, medical research, and many other aspects of health. Medicine aims to promote and maintain health and wellbeing",
  "active": true,
  "department_id": 1,
  "created_at": "2022-08-13T20:01:14.000000Z",
  "updated_at": "2022-08-20T15:44:54.000000Z",
  "deleted_at": null,
  "pivot": {
    "pharmacy_id": 1,
    "medicine_id": 6,
    "id": 6,
    "price": "30.00",
    "amount": "30.00",
    "active": true
  }
}
*/

  int? id;
  String? name;
  String? photo;
  String? description;
  bool? active;
  int? departmentId;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  SearchModelDataDataPivot? pivot;

  SearchModelDataData({
    this.id,
    this.name,
    this.photo,
    this.description,
    this.active,
    this.departmentId,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.pivot,
  });

  SearchModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
    description = json['description']?.toString();
    active = json['active'];
    departmentId = json['department_id']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    deletedAt = json['deleted_at']?.toString();
    pivot = (json['pivot'] != null)
        ? SearchModelDataDataPivot.fromJson(json['pivot'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['photo'] = photo;
    data['description'] = description;
    data['active'] = active;
    data['department_id'] = departmentId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['deleted_at'] = deletedAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class SearchModelData {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 6,
      "name": "Medicine 6",
      "photo": "http://secret-taiga-11502.herokuapp.com/images/medicines",
      "description": "Medicine is the field of health and healing. It includes nurses, doctors, and various specialists. It covers diagnosis, treatment, and prevention of disease, medical research, and many other aspects of health. Medicine aims to promote and maintain health and wellbeing",
      "active": true,
      "department_id": 1,
      "created_at": "2022-08-13T20:01:14.000000Z",
      "updated_at": "2022-08-20T15:44:54.000000Z",
      "deleted_at": null,
      "pivot": {
        "pharmacy_id": 1,
        "medicine_id": 6,
        "id": 6,
        "price": "30.00",
        "amount": "30.00",
        "active": true
      }
    }
  ],
  "first_page_url": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1",
  "per_page": 10,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
*/

  int? currentPage;
  List<SearchModelDataData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<SearchModelDataLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  SearchModelData({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });

  SearchModelData.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SearchModelDataData>[];
      v.forEach((v) {
        arr0.add(SearchModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json['first_page_url']?.toString();
    from = json['from']?.toInt();
    lastPage = json['last_page']?.toInt();
    lastPageUrl = json['last_page_url']?.toString();
    if (json['links'] != null) {
      final v = json['links'];
      final arr0 = <SearchModelDataLinks>[];
      v.forEach((v) {
        arr0.add(SearchModelDataLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json['next_page_url']?.toString();
    path = json['path']?.toString();
    perPage = json['per_page']?.toInt();
    prevPageUrl = json['prev_page_url']?.toString();
    to = json['to']?.toInt();
    total = json['total']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['current_page'] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['first_page_url'] = firstPageUrl;
    data['from'] = from;
    data['last_page'] = lastPage;
    data['last_page_url'] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['links'] = arr0;
    }
    data['next_page_url'] = nextPageUrl;
    data['path'] = path;
    data['per_page'] = perPage;
    data['prev_page_url'] = prevPageUrl;
    data['to'] = to;
    data['total'] = total;
    return data;
  }
}

class SearchModel {
/*
{
  "status": true,
  "code": 200,
  "msg": "",
  "data": {
    "current_page": 1,
    "data": [
      {
        "id": 6,
        "name": "Medicine 6",
        "photo": "http://secret-taiga-11502.herokuapp.com/images/medicines",
        "description": "Medicine is the field of health and healing. It includes nurses, doctors, and various specialists. It covers diagnosis, treatment, and prevention of disease, medical research, and many other aspects of health. Medicine aims to promote and maintain health and wellbeing",
        "active": true,
        "department_id": 1,
        "created_at": "2022-08-13T20:01:14.000000Z",
        "updated_at": "2022-08-20T15:44:54.000000Z",
        "deleted_at": null,
        "pivot": {
          "pharmacy_id": 1,
          "medicine_id": 6,
          "id": 6,
          "price": "30.00",
          "amount": "30.00",
          "active": true
        }
      }
    ],
    "first_page_url": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://secret-taiga-11502.herokuapp.com/api/v1/search/pharmacy/1",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
}
*/

  bool? status;
  int? code;
  String? msg;
  SearchModelData? data;

  SearchModel({
    this.status,
    this.code,
    this.msg,
    this.data,
  });

  SearchModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code']?.toInt();
    msg = json['msg']?.toString();
    data =
        (json['data'] != null) ? SearchModelData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['msg'] = msg;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
